name: Daily Scan Report

on:
  #schedule:
  #  - cron: '42 14 * * *' #TODO: it does not work for no reason
  #    timezone: "Asia/Shanghai"
  workflow_dispatch:

jobs:
  report:
    runs-on: self-hosted
    env:
      GIT_AUTHOR_NAME: "github-actions[bot]"
      GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      GIT_COMMITTER_NAME: "github-actions[bot]"
      GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
    steps:
      - name: Run analysis
        working-directory: /home/yzs/riscv/rv-isa-sec
        run: bash scripts/daily-analyze.sh